### ISSUE TITLE
Different size of MP library

### ISSUE THREAD

**Issue by ascendo** [ksahlin/BESST#11]
Dear Kristoffer,

Hi!

I am Won in University of Nevada, Reno.

I try to run BBEST and I have 2 different insert size MP library.

Is there any example for mapping?

Also at the note

"Mapping reads: If you want to map a mate pair library, you will need to map them as paired end library i.e. forward-reverse mode. All read pair libraries should be in this order. "

Do I need to mapping as paired end mode and use fr orientation?

Thank you.

**Comment by ksahlin** [comment]
Hi Won,

In the folder "scripts", there is a script called "reads_to_ctg_map.py" that runs the mapping for you. Currently, you can choose either to map with bwa-sampe or bwa-mem. Im assuming you have files like lib1_A.fq, lib1_B.fq, lib2_A.fq, lib2_B.fq  (or fasta format). That is, reads are split up into two files for each library. Then I would run  "reads_to_ctg_map.py" twice like:

python reads_to_ctg_map.py   /path/to/lib1_A.fq  /path/to/lib1_A.fq  /path/to/contigs.fasta  --threads <N> 

python reads_to_ctg_map.py   /path/to/lib2_A.fq  /path/to/lib2_A.fq  /path/to/contigs.fasta  --threads <N>

where N could e.g. be set to the number of cores you have available (it decides the number of threads for bwa-mem). To use bwa-sampe, just add the parameter --nomem. Sorting and indexing the bam-file is performed automatically in this pipeline. BESST is more thoroughly tested by me with the with bwa-sampe pipeline but it also takes longer time to map with this method. That said it does not not necessarily perform worse or better with any one of them. Mappings from Bowtie/bowtie2 could also be used but you would have to performe those steps yourself with the guidance of the bowtie manual on how to map pared reads.

"Mapping reads: If you want to map a mate pair library, you will need to map them as paired end library i.e. forward-reverse mode. All read pair libraries should be in this order. "

This is for an older version of besst. With besst >=1.3 you can map in any orientation. Just make sure when you call besst to set the --orientation parameter. If you have one fr and one rf library (mapped in that order), i.e. a paired end and a mate pair library, you can run besst as:

runBESST -c /path/to/contigfile.fa -f /path/to/file1.bam /path/to/file2.bam -o /path/to/output --orientation fr rf

(See https://github.com/ksahlin/BESST/blob/master/docs/MANUAL.md)


Hope this helps and I wish you a productive new year!

**Comment by ksahlin** [comment]
edit: it should be --threads N in the command line to "reads_to_ctg_map.py", where N is set to an integer
