### ISSUE TITLE
Contigs singeled out due to length constraints

### ISSUE THREAD

**Issue by sarasumic** [ksahlin/BESST#12]
Hello,

I am running BESST on quite a fragmented assembly (N50 ~ 3400) and long jumping distance reads with and insert size of 3kb, mapped with BWA in paired end mode. I do not get much of them scaffolded, and the only suspicious thing I can see in the Statistics.txt file is that a very large number of contigs was 'singeled out due to length constraints':

Parsing BAM file...
L50:  23569 N50:  3401 Initial contig assembly length:  321680008
Time adding 100k keys 0.70676112175
Time adding 100k keys 0.761782884598
Nr of contigs that was singeled out due to length constraints 147845
Time initializing BESST objects:  1.64816403389
Nr of contigs/scaffolds included in scaffolding: 10459

I can't seem to fix this, if it is an issue leading to the quite poor scaffolding. I would greatly appreciate any help or suggestions.

Best regards,
Sara Sumic

**Comment by ksahlin** [comment]
Hi Sara,
I'm happy to help you with this. If you could sent the Statistics.txt to ksahlin@kth.se, I can infer what is going on. 

Best,
Kristoffer
