### ISSUE TITLE
reads_to_ctg_map.py: temp files are not deleted

### ISSUE THREAD

**Issue by pascal-git** [ksahlin/BESST#15]
I detected that my tmp folder was filling up rapidly. I could pinpoint the problem to reads_to_ctg_map.py not cleaning up when its done. The full sam files are left in the tmp folder. I tweaked the script for a hotfix on my local machine but this probably should be checked thoroughly and for the different possible alignment algorithms...

**Comment by pascal-git** [comment]
This is the hotfix i tried: (the ```os.remove ``` statements in the end of the function)

```python
def bwa_mem(pe1_path, pe2_path, genome_path, threads, output_path):
    print 'Aligning with bwa mem'
    start = time()
    work_dir = tempfile.mkdtemp()
    genome_db = os.path.join(work_dir, "genome")
    pe1_output = os.path.join(work_dir, "pe1.sai")
    pe2_output = os.path.join(work_dir, "pe2.sai")
    bwa_output = os.path.join(work_dir, "output.sam")
    stderr_file = open(output_path+'.bwa.1','w')

    #null = open("/dev/null")
    subprocess.check_call([ "bwa", "index", "-p", genome_db, genome_path ], stderr=stderr_file)
    with open(bwa_output, "w") as bwa_file:
        subprocess.check_call([ "bwa", "mem", "-t", threads,
                                genome_db, pe1_path, pe2_path ],
                              stdout=bwa_file,
                              stderr=stderr_file)

    elapsed = time() - start
    print 'Time elapsed for bwa mem: ', elapsed
    sam_to_bam(bwa_output, bwa_output + ".bam")
    pysam.sort(bwa_output + ".bam", output_path)
    pysam.index(output_path + '.bam')
    os.remove(genome_db)
    os.remove(pe1_output)
    os.remove(pe2_output)
    os.remove(bwa_output)
    os.rmdir(work_dir)
```

However it did for some reason not solve the problem that the temporary files were left behind. So instead of ```reads_to_ctg_map.py``` i went for the direct use of ```bwa mem``` in my pipeline.

**Comment by mfranberg** [comment]
The problem is that os.rmdir(work_dir) only removes the directory if all files are gone. I think shutil.rmtree(work_dir) should do the trick, and submitted a fix for it. Nice catch!
