### ISSUE TITLE
KeyError: 11012

### ISSUE THREAD

**Issue by fbemm** [ksahlin/BESST#19]
I wanted to test the new BESST version that can deal with PE reads in MP datatsets.

Running BESST (developer version) results in a crash:

Constructed contig graph. Start BESST algorithm for creating scaffolds. 
Traceback (most recent call last):
  File "/besst/runBESST", line 391, in <module>
    main(args)
  File "/besst/runBESST", line 186, in main
    MS.Algorithm(G, G_prime, Contigs, small_contigs, Scaffolds, small_scaffolds, Information, param)   # Make scaffolds, store the complex areas (consisting of contig/scaffold) in F, store the created scaffolds in Scaffolds, update Contigs
  File "/besst/BESST/MakeScaffolds.py", line 86, in Algorithm
    (Contigs, Scaffolds, param) = NewContigsScaffolds(G, G_prime, Contigs, small_contigs, Scaffolds, small_scaffolds, Information, dValuesTable, param, already_visited)   #step5
  File "/besst/BESST/MakeScaffolds.py", line 283, in NewContigsScaffolds
    PROWithinScaf(G, G_prime, Contigs, small_contigs, Scaffolds, small_scaffolds, param, new_scaffold_, dValuesTable, already_visited)
  File "/besst/BESST/MakeScaffolds.py", line 534, in PROWithinScaf
    G_, path = estimate_path_gaps(Contigs, small_contigs, high_score_path_copy,Scaffolds,small_scaffolds, G_prime,param)
  File "/besst/BESST/MakeScaffolds.py", line 1018, in estimate_path_gaps
    constraint_pairs = kmer_overlaps(path, Scaffolds, small_scaffolds, Contigs, small_contigs)
  File "/besst/BESST/MakeScaffolds.py", line 891, in kmer_overlaps
    ctg = Scaffolds[label[0]].contigs[-1]
KeyError: 11012

**Comment by fbemm** [comment]
That was the log output until it crashed:

Time elapsed for reading in contig sequences:1.60171794891

PASS 1
Mean before filtering : 7436.0693971
Std_est  before filtering:  1942.93990459
Mean converged: 7430.37743986
Std_est converged:  1118.4498456
Contamine mean before filtering : 310.003900636
Contamine stddev before filtering:  2829.43464628
Contamine mean converged: 4.5
Contamine std_est converged:  2.12132034356

LIBRARY STATISTICS
Mean of library set to: 7430.37743986
Standard deviation of library set to:  1118.4498456
MP library PE contamination:
Contamine rate (rev comp oriented) estimated to:  False
lib contamine mean (avg fragmentation size):  0
lib contamine stddev:  0
Number of contamined reads used for this calculation:  2
-T (library insert size threshold) set to:  11904.1768223
-k set to (Scaffolding with contigs larger than):  11904.1768223
Number of links required to create an edge:  3
Read length set to:  131.94

Time elapsed for getting libmetrics, iteration 0: 137.097656012

Parsing BAM file...
L50:  381 N50:  86876 Initial contig assembly length:  138636136
Nr of contigs that was singeled out due to length constraints 46314
Time initializing BESST objects:  0.396004915237
Nr of contigs/scaffolds included in scaffolding: 1473
Total time elapsed for initializing Graph:  0.75382399559
Reading bam file and creating scaffold graph...
ELAPSED reading file: 427.312476873
NR OF FISHY READ LINKS:  0
Number of USEFUL READS (reads mapping to different contigs uniquly):  3975823
Number of non unique reads (at least one read non-unique in read pair) that maps to different contigs (filtered out from scaffolding):  7862348
Reads with too large insert size from "USEFUL READS" (filtered out):  917330
Number of duplicated reads indicated and removed:  180163
Mean coverage before filtering out extreme observations =  58.657575424
Std dev of coverage before filtering out extreme observations=  65.8335689414
Mean coverage after filtering =  55.5569604583
Std coverage after filtering =  9.6874456994
Length of longest contig in calc of coverage:  1006785
Length of shortest contig in calc of coverage:  28050
Detecting repeats..
Removed a total of:  10189  repeats.
Number of BWA buggy edges removed:  0
Number of significantly spurious edges: 0
Number of fishy edges in G_prime 37224
Total time for CreateGraph-module, iteration 0: 436.76983285

6855 link edges created.
Perform inference on scaffold graph...
Remove isolated nodes.
0 isolated contigs removed from graph.
Remove edges from node if more than two edges
SCORES AMBVIVALENT 1.88436573897 1.77319308191
SCORES AMBVIVALENT 1.58653951728 1.56742940291
SCORES AMBVIVALENT 1.86851882829 1.71307592781
SCORES AMBVIVALENT 1.58416085009 1.58097535545
SCORES AMBVIVALENT 1.85886774233 1.73001707403
SCORES AMBVIVALENT 1.8575953515 1.74067486588
SCORES AMBVIVALENT 1.85382738253 1.83308730315
SCORES AMBVIVALENT 1.84417199364 1.6822624932
SCORES AMBVIVALENT 1.64413170043 1.5099333584
SCORES AMBVIVALENT 1.83261560478 1.72499445767
SCORES AMBVIVALENT 1.81893934952 1.70480197021
SCORES AMBVIVALENT 1.81820660565 1.78760141432
SCORES AMBVIVALENT 1.81585982701 1.68617394735
SCORES AMBVIVALENT 1.81145692585 1.79471189384
SCORES AMBVIVALENT 1.80485870403 1.65721727912
SCORES AMBVIVALENT 1.76393431184 1.58808464193
SCORES AMBVIVALENT 1.74919996667 1.61991370991
SCORES AMBVIVALENT 1.748968206 1.58042587151
SCORES AMBVIVALENT 1.74685301845 1.58046514253
SCORES AMBVIVALENT 1.73738977157 1.57463800295
SCORES AMBVIVALENT 1.73068503862 1.6043646469
SCORES AMBVIVALENT 1.69520269225 1.54711109016
SCORES AMBVIVALENT 1.65570874535 1.50523454774
SCORES AMBVIVALENT 1.49353564002 1.40575812567
SCORES AMBVIVALENT 1.55819352233 1.51080597427
SCORES AMBVIVALENT 1.53498042263 1.51478248915
SCORES AMBVIVALENT 1.52063788279 1.50859647107
SCORES AMBVIVALENT 1.5063835247 1.39953653137
SCORES AMBVIVALENT 1.48605872897 1.47381550676
SCORES AMBVIVALENT 1.4846695413 1.45849949658
SCORES AMBVIVALENT 1.47114704489 1.37091307507
SCORES AMBVIVALENT 1.37309697574 1.2899753814
 Number of edges in G before: 8306
 Number of edges in G after: 2515
 %-age removed edges: 69.720683843
Remove isolated nodes.
126 isolated contigs removed from graph.
Contigs/scaffolds left: 1325
Remove remaining cycles...
0 cycles removed from graph.
Nr of new scaffolds created in this step: 261

**Comment by ksahlin** [comment]
Hi,

Try the master branch, it handles PE-reads in MP dataset. The develop is simply not stable -- but thank you for showing me a bug on develop!

On another note, does the mean and standard deviation in Statistics.txt look ok to you?  I wonder since besst sees only 2 PE-contaminatied reads in the data set (If you expect more PE reads maybe..?)
