### ISSUE TITLE
Usage of -q argument

### ISSUE THREAD

**Issue by sidorov-si** [ksahlin/BESST#24]
Dear Dr. Sahlin,

Trying to use -q argument in order to parallelize paths finding I got the following error (copied it with two additional lines above):

Total nr of paths found: 3290 with score larger than: 1.5
Exit Worker-6
Traceback (most recent call last):
  File "/home/ssidorov/tools/BESST/runBESST", line 395, in <module>
    main(args)
  File "/home/ssidorov/tools/BESST/runBESST", line 187, in main
    MS.Algorithm(G, G_prime, Contigs, small_contigs, Scaffolds, small_scaffolds, Information, param)   # Make scaffolds, store th
e complex areas (consisting of contig/scaffold) in F, store the created scaffolds in Scaffolds, update Contigs
  File "/home/ssidorov/tools/BESST/BESST/MakeScaffolds.py", line 91, in Algorithm
    PROBetweenScaf(G_prime, Contigs, small_contigs, Scaffolds, small_scaffolds, param, dValuesTable, Information)
  File "/home/ssidorov/tools/BESST/BESST/MakeScaffolds.py", line 892, in PROBetweenScaf
    worker.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 120, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

Information about the situation:

1. I have 9 libraries of a vertebrate: 3 paired-end and 6 mate-paired.
2. Total amount of libraries is 735 GB.
3. Number of initial contigs is 6845757.
4. I launched BESST as follows:

/home/ssidorov/tools/BESST/runBESST \
-c contigs.fa \
-f lib1.bam lib2.bam lib3.bam lib4.bam lib5.bam lib6.bam lib7.bam lib8.bam lib9.bam \
--orientation fr fr fr rf rf rf rf rf rf \
-o out_dir \
-q

where lib1, lib2 and lib3 are paired-end and lib4, ..., lib9 are mate-paired.

The process that issued this error didn't stopped though, and I found another 6 BESST python processes that aquired 514.8 GB of virtual memory in total. I didn't noticed any other errors.

I failed to find any other options for parallelization (e. g., max threads/processes number or max total amount of memory that can be used). Could it be implemented in some further versions of BESST?

**Comment by ksahlin** [comment]
Hi,

Thanks for your reporting! I will address your issues in the next master version soon to be pushed. -q option has a known bug that you experienced and I will remove that option in the next push until I've fixed it. In the meantime I advice you not to use it. Also, I'm happy to help you get the most from BESST regarding the scaffolding. You're welcome to mail me (mailadress in the publication of BESST) with the data and status of your project. I'm concerned that maybe it's better to actually give less libraries in input in your case (depending on initial assembly quality and the insert sizes of your libraries).

Best,
Kristoffer

**Comment by sidorov-si** [comment]
Hi Kristoffer,

Thank you very much for your quick reply and suggestions!
I'll let you know about my experience with BESST without -q.

Best regards,
     Slava


2015-10-23 14:43 GMT+03:00 Kristoffer <notifications@github.com>:
