### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by peterdfields** [ksahlin/BESST#29]
I'm observing the following error when trying to scaffold a relatively small assembly currently in 10 contigs:

Traceback (most recent call last):
  File "/home/peter/bioinformatics/BESST/runBESST", line 401, in <module>
    main(args)
  File "/home/peter/bioinformatics/BESST/runBESST", line 160, in main
    libmetrics.get_metrics(bam_file, param, Information)
  File "/home/peter/bioinformatics/BESST/BESST/libmetrics.py", line 376, in get_metrics
    param.lognormal_sigma = math.sqrt(param.lognormal_mean - math.log(mode_adj))
ValueError: math domain error

**Comment by ksahlin** [comment]
Hi, Sorry for the late reply. I have time to look into this now. Could you please send med the Statistics.txt file generated under BESST_output folder?

**Comment by peterdfields** [comment]
No worries. The following is all that was reported in the Statistics.txt file:

Time elapsed for reading in contig sequences:0.0019199848175


PASS 1


Mean before filtering : 36825.7053859
Std_est  before filtering:  81220.3108191
Mean converged: 18188.8750539
Std_est converged:  34188.8031462
Skewness of distribution:  1.82330099263
mode for chunk size  1  :  75170.5
mode for chunk size  6  :  75171.0
mode for chunk size  11  :  75168.5
mode for chunk size  16  :  75176.0
mode for chunk size  21  :  75169.5
mode for chunk size  26  :  75179.0
mode for chunk size  31  :  75159.5
mode for chunk size  36  :  75186.0
mode for chunk size  41  :  75173.5
mode for chunk size  46  :  75187.0
mode for chunk size  51  :  75148.5
mode for chunk size  56  :  75180.0
mode for chunk size  61  :  75182.5
mode for chunk size  66  :  75141.0
mode for chunk size  71  :  75153.5
mode for chunk size  76  :  75202.0
mode for chunk size  81  :  75208.5
mode for chunk size  86  :  75207.0
mode for chunk size  91  :  75211.5
mode for chunk size  96  :  75216.0
mode for chunk size  101  :  75194.5
Mean of getdistr adjusted distribution:  28244.3788448
Sigma of getdistr adjusted distribution:  41634.8683258
Skewness of getdistr adjusted distribution:  1.20303579485
Median of getdistr adjusted distribution:  1090
Mode of getdistr adjusted distribution:  75179
Using mean and stddev of getdistr adjusted distribution from here:  28244.3788448 41634.8683258
Mode on getdistr adjusted:  75179
Median on getdistr adjusted: 1090

**Comment by ksahlin** [comment]
What type of library is it and what mean and standard deviation are you expecting of the read pair distribution approximately?

**Comment by peterdfields** [comment]
It's a Nextera MiSeq (300bp PE), with an average insert size of 450 and std. dev. of 70.

**Comment by ksahlin** [comment]
Ok, then the estimation in BESST is way off. I think that BESST gets is estimations from reads that are mapped in the reverse complementary orientation. This usually means that the orientation of the mappings are given incorrectly. 

Have you tried specified the orientation of the read pair mappings using --orientation ? What are your command line arguments by the way?

**Comment by peterdfields** [comment]
The basic command I'm running is as follows:

runBESST -c contigfile.fa -f file1.bam -o output --orientation fr

I can try adding the expected insert size and std. dev. to see if that helps.

**Comment by ksahlin** [comment]
Try running also with --orientation rf to see what happens. Is it possible by some chance that they have been reverse complemented before aligned? I've seen this happen before. Also I've seen one case where only one file had been rc, so that the true pairs were in ff orientation. I should probably include writing information about all possible orientations in the log file to avoid these kind of error searches...

**Comment by ksahlin** [comment]
I've uploaded a new version of BESST today that includes improvements I did around February. It will probably not fix the bug that you are experiencing but just to let you know that it might be worth updating to this version.

**Comment by ksahlin** [comment]
I've now fixed the bug you reported in latest commit to master + latest version on pip!

However, this fix only takes care of the math domain error reported. The discrepancy between insert size reported by BESST, and the distribution you expect i.e., PE 450bp mean, signals that there is something about either mappings or orientation assumptions that is wrong --- as I mentioned earlier.

**Comment by ksahlin** [comment]
Closing this now as I think it's fixed. Please reopen if you decide to test this and and still get the error with the new version.
