### ISSUE TITLE
mathstats

### ISSUE THREAD

**Issue by phpeters** [ksahlin/BESST#31]
Hej Kristoffer!

When building and installing the mathstats package, I get the error
IOError: [Errno 2] No such file or directory: u'/software/python/Python2.7/lib/python2.7/site-packages/mathstats-0.2.3/README.md'

After commenting out the line 
long_description=open(os.path.join(os.getcwdu(), 'README.md')).read(),
in the setup.py file, everything worked fine.

Greets from Vienna,
Philipp

**Comment by ksahlin** [comment]
Hej!

Thanks for reporting. Ok great I know what the issue is and I have fixed that now (in mathstats v0.2.4). Please let me know if you can install mathstats v0.2.4 sucessfully.

Kristoffer

**Comment by phpeters** [comment]
Nice! Seems to work smoothly! Thanks a lot!
Philipp
