### ISSUE TITLE
does repeats fasta contain all detected repeats?

### ISSUE THREAD

**Issue by albodrug** [ksahlin/BESST#32]
Hello, 

I am using BESST with 5 mate pair libraries. The repeats.fa file is created when reading the first mate pair library with the smallest insert. Are repeats detected thanks to the libraries or is this a separate step using only the genome information given to BESST?

Thanks

**Comment by ksahlin** [comment]
Hi,

repeats.fa is a temporary file created by BESST to store all the contigs that were classified as repeats. If the parameter `--separate_repeats` is not specified, the repeats.fa will be merged back into the Scaffolds_passX.fa file -- and the file will disappear after scaffolding is completed. If  `--separate_repeats`  specified, it will remain as separate file in the final output, and these contigs wont be included in Scaffolds_passX.fa

There is also a file `BESST_output/repeats_log.tsv` that outputs information of the repeats such as contigs accession, length, average coverage, for logging purposes. Ultimately, this file would serve as guidance to the repeats that can be placed in multiple places in gaps within scaffolds, but I have not implemented this step yet.

**Comment by albodrug** [comment]
Thanks for the quick reply. Do you classify the contigs as repeats according to the coverage in the bam files or some other additional criteria? 
Personally I do not specify --separate_repeats so I was wondering why it disappears at the end.

**Comment by ksahlin** [comment]
No additional criteria to coverage in the bam file is currently used. It's my intent to combine the coverage information with information based on the structure of the graph around the contig.
