### ISSUE TITLE
Please tag a stable release of 2.2.4

### ISSUE THREAD

**Issue by sjackman** [ksahlin/BESST#35]
The most recent tag on GitHub is 2.1, but the most recent tag on PyPI is 2.2.4.

**Comment by ksahlin** [comment]
If solution to https://github.com/ksahlin/BESST/issues/33 works, I will tag v2.2.5 as stable release. This version fixes a runtime bug in 2.2.4 and contains no other updates.

**Comment by sjackman** [comment]
Great. Would you also like to tag 2.2.4 in the mean time?

**Comment by ksahlin** [comment]
Ok, I just tagged 2.2.4.
