### ISSUE TITLE
Is the final scaffolds in BESST_output/pass1/Scaffolds_pass1.fa?

### ISSUE THREAD

**Issue by sjackman** [ksahlin/BESST#36]
`BESST_output/pass1/Scaffolds_pass1.fa` is the most recent file output by BESST. I thought that I had read there were three passes. The NG50 of this file is good (7 Mbp for human).

**Comment by ksahlin** [comment]
There should be one pass for each library used, e.g., if five read pair libraries are used the final output is in pass5/Scaffolds_pass5.fa. For one lib, the final output is in pass1.

**Comment by sjackman** [comment]
Got it. Thanks for the clarification.
