### ISSUE TITLE
"too few data" detection

### ISSUE THREAD

**Issue by sletort** [ksahlin/BESST#37]
/!\ My Error /!\
I used the full contigs as fasta file with a reduced bam file.
This where comes from the pb.

Just ignore this.

=======================================
Hi Kristoffer,

While trying to reproduce the "zero division issue" on a small set, I encounter another "float division by zero".
The first one appear on line 63 of GenerateOutput.py.
I modified the code to replace value round(cont_obj.coverage/param.mean_coverage,0) by "NA" if param.mean_coverage was equal to 0.
But after that, another error appear on line 65 of e_nr_links.py

I do not have a global view of the program, but I think that you should detect the case of "too few data" as early as possible, and stop computation with an error.

regards,

**Comment by ksahlin** [comment]
ok, good! Please see possible solution to the zero division issue in https://github.com/ksahlin/BESST/issues/33
