### ISSUE TITLE
skip orientation ... as there are not enough pairs

### ISSUE THREAD

**Issue by mebbert** [ksahlin/BESST#39]
Kristoff,

Thank you for your assistance using BESST. I actually have a question regarding BWA, but it affects how I use BESST. I hope you can help.

I have three mate-pair libraries (3kb, 7kb, and 10kb), and I aligned them individually to a Discovar de novo (DDN) assembly set (known as a.fasta for DDN). I looked through the BWA log and found the following log messages for _**every**_ set of reads that BWA read in:

> [M::process] read 482534 sequences (120000246 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 0, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs

I don't know if that should alarm me or not. Is that normal with a mate-pair library being aligned to an assembly? I can't find any official documentation on when this warning comes up or how it's determined. Maybe that happens when the pairs map to different contigs?

Based on that, what would I specify as the orientation to BESST? I imagine the bams have both FR and RF orientations. Can best discern between FR and RF?

Thanks!

**Comment by ksahlin** [comment]
Yes, this is alarming and this is not what BESST expects. BESST expects the read pairs to be mapped as pairs. It seems as bwa does not recognize any pairs in your output.  How did you run bwa to produce this output?

**Comment by mebbert** [comment]
Thanks for the quick response!

I'm using your script `reads_to_ctg_map.py` Here is the command for the 3kb library:

`python reads_to_ctg_map.py --clear --threads 12 ../../G12-3_S4_R1_001.fastq.gz ../../G12-3_S4_R2_001.fastq.gz ../a.final/a.fasta mate_pair_alignments/G12-3kb`

Do you know how BWA identifies the pair orientation? I double checked that the R1 and R2 reads are properly named. Here's the first entry in both files:

**R1**
> @D00723:88:HNK23BCXX:1:1103:1233:2150 1:N:0:TGACCA

**R2**
> @D00723:88:HNK23BCXX:1:1103:1233:2150 2:N:0:TGACCA

**Comment by mebbert** [comment]
I wonder if I should be aligning to the Discovar de novo _scaffolds_ file instead of the raw contigs. I went with the raw contigs because another scaffolder took issue with the 'N' nucleotides in the scaffold. Does BESST have an issue with that?

**Comment by ksahlin** [comment]
Oh, thats weird. Everything looks ok. So, that makes me wonder about the contigs. The directions of pairs can only be inferred for pairs mapping to the same contig. So, do you have enough contigs larger than the distance of the pairs? What is the N50 for example?

**Comment by ksahlin** [comment]
No it does not have an issue with N's. I would recommend to try both strategies (feeding contigs/scaffolds) in case you get the alignments to contigs to work.

**Comment by mebbert** [comment]
That must be the problem. I just calculated N50 on the raw contigs file: 2681. N50 on the scaffolds file is 36823.

I'll align to the scaffolds file (a.lines.fasta) and report back. I'm guessing DDN doesn't provide an intermediate file of the full assembly *before* scaffolding. 

Thanks!

**Comment by ksahlin** [comment]
Ok, great. It seems strande though that "BWA log and found the following log messages for **every** set of reads .." Because surely there must be some long contigs (the longest ones) being significantly over 3kb. So you still might want keep that in mind, and compare with the stats you get when aligning to the scaffolds.

Closing this question now. You can always reopen it, or let me know if other issues occur. 
Thanks
