### ISSUE TITLE
IndexError wite mate paire library

### ISSUE THREAD

**Issue by albodrug** [ksahlin/BESST#41]
Hello, 

BESST works file with 4 of my 5 mate pair libraries, then I get this error for my largest insert size library. Could you please provide some help?
Thanks
Alex

```
>BESST -c Qpac.fasta -f mp8175_sorted.bam --orientation rf
Number of initial contigs: 6747
Choosing mode: 8127
mu_adjusted:8978.08200519, sigma_adjusted:1435.7464018, skewness_adjusted:0.657287834998
mode adj: 8127
median adj 8717
Creating contig graph with library:  mp8175_sorted.bam
Traceback (most recent call last):
  File "/software/BESST/BESST-2.2.2/runBESST", line 415, in <module>
    main(args)
  File "/software/BESST/BESST-2.2.2/runBESST", line 177, in main
    (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds and store them in F
  File "/software/BESST/BESST-2.2.2/BESST/CreateGraph.py", line 300, in PE
    GiveScoreOnEdges(G, Scaffolds, small_scaffolds, Contigs, param, Information, plot)
  File "/software/BESST/BESST-2.2.2/BESST/CreateGraph.py", line 538, in GiveScoreOnEdges
    std_dev_d_eq_0 = conditional_stddevs[int(gap)]
IndexError: list index out of range
```

**Comment by dbrowneup** [comment]
I am having the same error with my 15kb mate pair library. The error is occurring in the [GiveScoreOnEdges function](https://github.com/ksahlin/BESST/blob/c6687f54da7f0208ec625baf8f1a8030e9ebd8b0/BESST/CreateGraph.py#L464), specifically [line 538](https://github.com/ksahlin/BESST/blob/c6687f54da7f0208ec625baf8f1a8030e9ebd8b0/BESST/CreateGraph.py#L538). I can't really spot the problem right now and it will take some time to understand the code. But I think that running --no_score should let us get around the problem until it is fixed.

**Comment by KamilSJaron** [comment]
I have exactly this issue. Is it know what it is causing it?

**Comment by melop** [comment]
Hello, I report the same problem in one of my libraries.

**Comment by KamilSJaron** [comment]
@melop the pseudo-solution of @dbrowneup have worked for me (if you are wondering about quick fix).

**Comment by melop** [comment]
After reading the code, I feel confused about the lines 481-482 in CreateGraph.py:
 
steps = range(0, int(max_isize*0.8), max_isize/50)  
conditional_stddevs = get_conditional_stddevs(steps, emp_distr, max_isize)

        Here the **steps** array is in the range 0 ~ max gap size, with a step of max gap size / 50. I think then get_conditional_stddevs returns a dictionary with the keys being the gap size and the values being the conditional std. However, I am not sure why the step size in here is not 1 and the max value is not simply max_isize. In the place where the code crashes you see:

std_dev_d_eq_0 = conditional_stddevs[int(gap)]

        It seems that the **gap** size estimated is simply not found in the prebuilt dictionary conditional_stddevs, due to the fact that the index does not necessarily increase by 1 and the max index does not reach max gap size.

        Could someone maybe confirm?

Ray

**Comment by melop** [comment]
ok, so I changed the lines 535 - 540 in CreateGraph.py, basically checking the upper index boundary and assign the last value in the list in case the gap is larger than the upper bound:

            if 2 * param.std_dev_ins_size < len1 and 2 * param.std_dev_ins_size < len2:
                if param.lognormal:
                    if gap > 0 and gap < len(conditional_stddevs) :
                        std_dev_d_eq_0 = conditional_stddevs[int(gap)]
                    elif gap >= len(conditional_stddevs)  :
                        std_dev_d_eq_0 = conditional_stddevs[-1]
                    else:
                        std_dev_d_eq_0 = conditional_stddevs[0]

This seems to allow the program to continue running. But it still seems weird that "gap" would be out of bound. Hopefully Kristoffer can take a look at this soon...
