### ISSUE TITLE
BESST freezes after step 1

### ISSUE THREAD

**Issue by KamilSJaron** [ksahlin/BESST#44]
Hi, I am trying to use BESST, I have used the script `reads_to_ctg_map.py` to create input files from mp. Then I run

```sh
export PYTHONPATH='/home/kjaron/src/BESST/BESST'
/usr/bin/time -f '%M %E %P' python ~/src/BESST/runBESST -c my_genome.fa -f mp_lib1.bam mp_lib2.bam -o output.fa --orientation rf rf
```

Seems that the first iteration have worked (I can find several files in output directory):

```
$ls *
haplotypes.fa  repeats.fa  repeats_log.tsv  Statistics.txt

pass1:
info-pass1.agp  info-pass1.gff  Scaffolds_pass1.fa
```

Only `haplotypes.fa` is an empty file. However, stript does not continue, it just have frozen... (the memory is still allocated, but it is not an active process). end of the log:
```
enter Between scaf node:133700, scaffold progression 99.8%.
enter Between scaf node:133800, scaffold progression 99.8%.
enter Between scaf node:133900, scaffold progression 99.9%.
enter Between scaf node:134000, scaffold progression 100.0%.
Total nr of paths found: 73997 with score larger than: 1.5
Elapsed time single core pathfinder:  90.0153970718
Writing out scaffolding results for step 1  ...
```

Seems that it is trying to write something, I am not sure what... There is enough space on the disk. The only thing what came to my mind is, that I have used a dot in output name...

**Comment by KamilSJaron** [comment]
Sorry, my fault.

I was running it in screen, I wanted to check history of log, so I went to copy mode, at some point he was sunning out of number of lines that are kept by screen so screen just stopped the process, when I have escaped the copy mode, process started to compute again.

(it is really terrible how our embarrassment is public in now days).

**Comment by ksahlin** [comment]
No worries, it happens to everyone :) I'm glad that it works!
