### ISSUE TITLE
Mate pair processing

### ISSUE THREAD

**Issue by ptranvan** [ksahlin/BESST#46]
Hi,

I don't understand why  `/path/to/lib1_A.fq` is specified twice in your code:

`python reads_to_ctg_map.py /path/to/lib1_A.fq /path/to/lib1_A.fq /path/to/contigs.fasta --threads N`

**Comment by ksahlin** [comment]
That's a typo, it should be `/path/to/lib1_b.fq`. Yes I reccoment using nxTrim before, even though BESST can handle PE contaminants, nevertheless, read alignments might be better after removal of adapters and chimeras.

**Comment by ptranvan** [comment]
Do you merge the MP and unknow libraries ?

**Comment by ksahlin** [comment]
It's not done by BESST but you can do it if the unknown fraction is large. "Unknown" is supposed to be mostly consisting of MP oriented reads. Remember that in the output format "mp", "pe" and "unknown" is all in fr orientation unless you set a flag to NxTrim not to switch orientation.
