### ISSUE TITLE
Unusual gap and merge numbers

### ISSUE THREAD

**Issue by dbrowneup** [ksahlin/BESST#50]
I'm a little confused about how these numbers add up and it makes me wonder if there is something strange going on.

I have a base assembly consisting of 38,828 contigs, which contain 764 gaps of 100 bp:
```bash
[dbrowne@ada2 BESST_output]$ abyss-fac -s 0 ../../B_DDN3_BASE-3.fa
n	n:0	L50	min	N80	N50	N20	E-size	max	sum	name
38828	38828	6181	1000	2418	5614	15428	89404	1739573	155.8e6	../../B_DDN3_BASE-3.fa
```

 After running BESST, I observe the formation of 22,034 new gaps in the final assembly:
```bash
[dbrowne@ada2 BESST_output]$ abyss-fac -s 0 pass4/Scaffolds-pass4.fa 
n	n:0	L50	min	N80	N50	N20	E-size	max	sum	name
5478	5478	117	1000	114096	325006	750170	648993	5353690	151.1e6	pass4/Scaffolds-pass4.fa
[dbrowne@ada2 BESST_output]$ grep -Eo "[N]+" pass4/Scaffolds-pass4.fa | awk '{i++} END{print i}'
22798
```

However, looking at the reported merges in the Statistics.txt file leaves me scratching my head:

```bash
[dbrowne@ada2 BESST_output]$ grep "merging" Statistics.txt | head
merging 199 bp here
merging 199 bp here
merging 55 bp here
merging 199 bp here
merging 31 bp here
merging 93 bp here
merging 199 bp here
merging 174 bp here
merging 199 bp here
merging 68 bp here
[dbrowne@ada2 BESST_output]$ grep "merging" Statistics.txt | wc -l
25733
```

If there were 25,733 ends merged, how can there also be 22,034 new gaps, when there were only 38,828 contigs to begin with, and 5,478 contig ends after scaffolding?

**Comment by ksahlin** [comment]
Are you scaffolding with several passes? Merging is a "finishing step" so it will be performed every pass before printing out. Within the algorithm the contigs are still kept as differnet objects, i.e., the same merge will de done before results are printed in each pass.

**Comment by dbrowneup** [comment]
Ah, I see. Yes I am scaffolding with 4 libraries and thus 4 passes. Thanks for the clarification!
