### ISSUE TITLE
Which contigs are joined to produce given scaffold?

### ISSUE THREAD

**Issue by PedroBarbosa** [ksahlin/BESST#62]
Hello, 

Thanks for the great tool, I would just suggest in a further release the report in the ouptut of the contigs IDs used to produce scaffold X., that would be really useful and informative feature.

Best,
Pedro

**Comment by ksahlin** [comment]
Hi Pedro,

Thanks! For each pass X, there are two files `info-passX.agp` and `info-passX.gff`in the same folder as the scaffold fasta file (`BESST_output/passX`). They both contain the annotations of the contigs to each scaffold. Let me know it that is sufficient for your purposes.

**Comment by PedroBarbosa** [comment]
That file is perfect, but I suppose that in output of the final pass, the agp file represents just the scaffolds that the bam from the last library could join, right? What about those ones that were scaffolded in the previous passes ? 

For example, I didn't undersand this next output:

`grep "PE150bp.genome2_contig-1284000033" info-pass3.agp
scaffold_1      0       4789    1       W       PE150bp.genome2_contig-1284000033       1       4790    -

grep "PE150bp.genome2_contig-1284000033" info-pass2.agp
scaffold_45     0       4789    1       W       PE150bp.genome2_contig-1284000033       1       4790    -
`
Thanks,
Pedro

**Comment by ksahlin** [comment]
No, the annotated contigs will always be the original contigs. However, the indexes of the scaffolds will change from pass to pass -- scaffolds between passes should not be compared. 

For instance, say that the first pass generated two scaffolds, 1 and 2, where scaffold 1 contains contigs 1,2,3 and scaffold2 contains  4 and 5. The next pass might scaffold the two scaffolds 1 and 2 into one, with index 1 (index are independent from pass to pass). In pass two, scaffold1 will consist of contigs 1,2,3,4,5 and they will be annotated to scaffold1 in `info-pass2.agp`.

Your example tells me that `scaffold_1` contains contig `PE150bp.genome2_contig-1284000033` in position 0 to 4789 and the contig is reverse complemented (w.r.t. the scaffold in the fasta file). This means you have to search for the reverse compement of the contig if you want to find it in the scaffold.

**Comment by PedroBarbosa** [comment]
Ok, got it. So, it brings me back to the original question (I should have mentioned I referred to the output of the last pass): Since this process is iterative, I can not trace back the original contigs that give rise to each scaffold on the final scaffolds.fasta, correct? 

Thanks you,
Pedro

**Comment by ksahlin** [comment]
You can: The original contig accessions (occurring in the input contigs.fa file) will occur in the final scaffolds in the agp file (and in all the ther passes as well). One line per contig. The agp file will tell you where the contig occurs in the final scaffold, its position and orientation. 

Can you confirm that this is the case with you final output?
