### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'edge'

### ISSUE THREAD

**Issue by yuragal** [ksahlin/BESST#64]
Hello,

When running BESST, I get the following error at the very beginning of computation:

```
$ runBESST -c contigs.fasta -f MP46.sorted.bam -orientation rf 
Number of initial contigs: 1043
Estimating insert size from 1000001 mappings with quality over --min_mapq 11.
Choosing mode: 4224
mu_adjusted:4639.9018121, sigma_adjusted:917.285704988, skewness_adjusted:2.18157522531
mode adj: 4224
median adj 4551
Creating contig graph with library:  MP46.sorted.bam
Traceback (most recent call last):
  File "/usr/local/bin/runBESST", line 424, in <module>
    main(args)
  File "/usr/local/bin/runBESST", line 177, in main
    (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds and store them in F
  File "/usr/local/lib/python2.7/dist-packages/BESST/CreateGraph.py", line 176, in PE
    is_dupl = CreateEdge(cont_obj1, cont_obj2, scaf_obj1, scaf_obj2, G, param, alignedread, counter, contig1, contig2)
  File "/usr/local/lib/python2.7/dist-packages/BESST/CreateGraph.py", line 841, in CreateEdge
    G.edge[(scaf_obj1.name, scaf_side1)][(scaf_obj2.name, scaf_side2)]['obs_sq'] = (obs1 + obs2) ** 2
AttributeError: 'Graph' object has no attribute 'edge'
```
[Statistics.txt](https://github.com/ksahlin/BESST/files/1425728/Statistics.txt)

Curiously, this error started to occur last day or two. Week before I have already had successful runs with the same MP library and scaffold sequences. Below are statistics of this run and logfile:
[Statistics.txt](https://github.com/ksahlin/BESST/files/1425734/Statistics.txt)
[BESST.log](https://github.com/ksahlin/BESST/files/1425735/BESST.log)

Except MP46, there were several other MP-libraries used, but these seem to have no influence on error discussed -- error constantly occur on the first graph construction step, regardless of the number of input libraries.

Could you please point me directions to get BESST running?

PS: Version of my python modules:
```
$ pip show BESST pysam networkx mathstats scipy | grep -A1 Name
Name: BESST
Version: 2.2.7
--
Name: pysam
Version: 0.12.0.1
--
Name: networkx
Version: 2.0
--
Name: mathstats
Version: 0.2.6
--
Name: scipy
Version: 1.0.0
```
OS:
```
$ uname -a
Linux desktop 3.13.0-105-generic #152-Ubuntu SMP Fri Dec 2 15:37:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Best, Yuri.

**Comment by yuragal** [comment]
Answering myself, the problem was in networkx 2.0. Versions 1.6-1.11 seem to work fine as well as the newest pysam version.

**Comment by ksahlin** [comment]
Hi,

Thanks for the detailed error log! You beat me to it. Yes, BESST is not supported for any networkx versions 2.0 and above due to big API changes [e.g. here](https://stackoverflow.com/questions/43054099/neighbors-g-neighbors-iter-attributeerror-graph-object-has-no-attribute-neig)

Possibly I will update to support versions >=2 if not too much work. As you mention, a fix is to install a networkx version 1.x.
