### ISSUE TITLE
reads_to_ctg_map.py: another error

### ISSUE THREAD

**Issue by bastianheimburger** [ksahlin/BESST#70]
Hi,

I've installed BESST using Python2.7. Once I am running the script 'reads_to_ctg_map.py', I get following error message:

  File "scripts/reads_to_ctg_map.py", line 62
    print('bwa index exists, no need to remake (--norebuildbwaindex specified)', end=' ')
                                                                                    ^
SyntaxError: invalid syntax

What is going wrong here?

Cheers Bastian

**Comment by rchikhi** [comment]
It seems that this line only works in Python3. That's indeed a problem

**Comment by rchikhi** [comment]
While you're at it, there is another error down the line (in both Python3 and Python2):

```
  File "/mnt/gpfs/rayanc/rayan/gatb-minia-pipeline/BESST/BESST/libmetrics.py", line 308, in get_metrics
    print >> Information, "Estimating insert size from {0} mappings with quality over --min_mapq {1}.".format(counter, param.min_mapq)
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

```

**Comment by ksahlin** [comment]
commit  038265c should fix both these issues

**Comment by rchikhi** [comment]
that was quick, thanks K!
