### ISSUE TITLE
filter bam for mapq score?

### ISSUE THREAD

**Issue by dcopetti** [ksahlin/BESST#72]
Hi,

I am doing the alignments to scaffold my sequences and I wonder if it is of any help to filter alignments that have MAPQ score above e.g. 40, or something like that.

I am dealing with a diploid assembly with many repeats and I want to avoid inter-allele or inter-repeat links. From analyses on the assembly k-mers I see that there are plenty of unique k-mers also in the repeat/TE regions (that should provide unique alignments), is that enough or should I parse in some way the bam file before BESST?
From the bwa-mem alignment (all default options), the majority of the flags I get so far are 99, 147, 63, 83 (20% each) and then 129, 65, 113, 177, 161, 81, 145, 97 (~2% each). Are these good proportions for BESST? Out of these, 55% have MAPQ<40 and 45% above it.

This is a 6 kb MP library and I have about 25x of it, then same amount for a 9 kb. My goal is to avoid any kind of false joints, so I would like to be as strict as possible in any step.
Thanks for the feedback!
Dario

**Comment by ksahlin** [comment]
Hi Dario,

I think it would hurt to filter reads prior, since BESST looks at coverage of contigs and it might distort the information. Hopefully most the inter-allele/repeat read pairs that were erroneously assigned have been labelled as mapq 0 (because multiple identical matches) and these reads are not used for scaffolding. BESST sets the default mapq for be over 10 (but could be lowered with `--min_mapq`). Also, wouldn't BWA prefer to assign the read pair to the same allele-contig in most cases?

The ones used for scaffolding are 129, 65, 113, 177, 161, 81, 145, 97. It is difficult-to-impossible to tell if proportions are good, as it depends on the contig-lengths (how much scaffolding is expected) and quality of contigs.

I can't remember how BWA calculates mapq for unique best hits with high scoring alternative alignment-sites, but if a low score is given because there is an alternative alignment that is only slightly worse (e.g., to the other allele), then you might want to lower `--min_mapq`. 

Hope this helps,
K

**Comment by dcopetti** [comment]
Hi,
Thanks for the suggestions.
I run BESST with a subset of the bam file to test the installation and the data, and I get this error;
runBESST -c genome.fa -f MP6_Rab2split_parts.bam -orientation rf -o test_6kb_small
/home/copettid/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:279: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Number of initial contigs: 1956915
[W::hts_idx_load2] The index file is older than the data file: MP6_Rab2split_parts.bam.bai
Estimating insert size from 1000001 mappings with quality over --min_mapq 11.
Choosing mode: 5037
mu_adjusted:5603.05203573, sigma_adjusted:823.780842794, skewness_adjusted:0.391976705224
Creating contig graph with library:  MP6_Rab2split_parts.bam
Traceback (most recent call last):
  File "/home/copettid/bin/BESST/runBESST", line 431, in <module>
    main(args)
  File "/home/copettid/bin/BESST/runBESST", line 182, in main
    (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds and store them in F
  File "/home/copettid/bin/BESST/BESST/CreateGraph.py", line 176, in PE
    is_dupl = CreateEdge(cont_obj1, cont_obj2, scaf_obj1, scaf_obj2, G, param, alignedread, counter, contig1, contig2)
  File "/home/copettid/bin/BESST/BESST/CreateGraph.py", line 844, in CreateEdge
    G.edge[(scaf_obj1.name, scaf_side1)][(scaf_obj2.name, scaf_side2)]['obs_sq'] = (obs1 + obs2) ** 2
AttributeError: 'Graph' object has no attribute 'edge'

I downloaded BESST from here and I had to install mathstats and pysam:
pip install mathstats
python2.7 -m pip install pysam

Is the file age an issue? It is because I downloaded them in that order from a remote server.
$ ls -rlth
total 3.3G
-rw-r----- 1 copettid mpb  77M Mar 13 11:29 MP6_Rab2split_parts.bam.bai
-rw-r----- 1 copettid mpb 3.2G Mar 13 11:30 MP6_Rab2split_parts.bam

For sure, there may be too little coverage from my input data: does this explain the issue?

**Comment by dcopetti** [comment]
I saw issue #64, I will try to install the older version of networkx.
:-(

**Comment by ksahlin** [comment]
Yes, networkx is the problem.  Let me know if you run into other problems.

**Comment by dcopetti** [comment]
Yep, now BESST works fine.

I am able to do some good scaffolding (I have 6 and 9 kb MP libraries) on my diploid assembly (est. haploid genome size 2.6 Gb, total assembly size 5 Gb, N50 196 kb, N80 5.4 kb, 1.55% Ns) and I get to a N50 of 365 kb, N80 10.7 kb, 1.67% Ns, 4.985 Gb total size. I am now checking the new scaffolding against a diploid optical map, that is my ground truth.

I am now running with --min_mapq 40 (I may try also 30 and 50), but my biggest concern is to keep the phasing after the scaffolding, i.e. to have an allele-specific scaffolding. I don't quite understand the meaning of the ploidy parameters (-a, -b, -g), could you please elaborate on that?

How else can I be more stringent? E.g. does --score_cutoff regulate the amount of links required to scaffold? maybe just very high MAPQ to avoid allelic variation?
Thanks!

**Comment by ksahlin** [comment]
I don't think allele specific scaffolding can be obtained with BESST as no phasing is considered.

The ploidy parameters was an experimental part of BESST where it tries to find, and output, one of the contigs in an allele split based on coverage and kmer-overlap between contigs. Based on the outputted contigs they could be removed from initial file before mapping and a single copy scaffolding cold be done (although it would be chimeric). I never thoroughly evaluated this function and couldn't recommend using it. Also it seems to not align with your goal.

Some parameters related to stringency are `-e` `-filter_contigs`, `--score_cutoff`.   `--score_cutoff` is the ratio between links supporting a path (i.e. scaffold) and contradicting the path. this could be set higher to do less scaffolding.

**Comment by dcopetti** [comment]
BESST works well for now - thanks!
One last question: in the agp file, what are the gaps of 1 nt?
scaffold_83_uid_1552567450      1       14215   1       W       scaffold21859:0-14215 1       14215   -
scaffold_83_uid_1552567450      14216   14216   2       N       1       scaffold        yes     paired-ends
scaffold_83_uid_1552567450      14217   20654   3       W       scaffold1799506:0-6438        1       6438    -
are they maybe negative gaps that are not resolved? 
Looking at some dotplots they don't look like.
Thanks!

**Comment by ksahlin** [comment]
Yes that is probably negative gaps that were not reslolved. If a gap is negatively estimated, BESST tries to "merge" ends by looking at exact kmer matches (up to 200bp can be set with `-max_contig_overlap`) but if no exact overlap is detected it will simply put the contigs with a gap of one bp. 

What you're seeing could maybe be longer overlaps due to the allele splitting going on..?
