### ISSUE TITLE
error about BESST/scripts/reads_to_ctg_map.py

### ISSUE THREAD

**Issue by Shirley-Q** [ksahlin/BESST#73]
There was an error that i could not solve it. Could you help me? Thank you very much!

Best wishes,
Shirley

**Comment by Shirley-Q** [comment]
The error was as followed.
Start processing.

Aligning with bwa mem.
Temp directory: /media/HD6/QXJ/minia-test/BESST_tmp
Output path:    assembly.lib_0
Stderr file:    assembly.lib_0.bwa.1
Make bwa index... Done.
Align with bwa mem... Traceback (most recent call last):
  File "/home/yuke/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py", line 360, in <module>
    tmp_path, args.bwa_path, args.clear, args.norebuildindex)
  File "/home/yuke/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py", line 178, in bwa_mem
    stderr=stderr_file)
  File "/home/yuke/miniconda2/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bwa', 'mem', '-t', '48', '-w', '0', '-O', '99', '/media/HD6/QXJ/minia-test/BESST_tmp/genome', 'bin3_seq_R1.fq', 'bin3_seq_R2.fq']' returned non-zero exit status 1
(2019-06-01 10:09:33) Execution of 'python BESST/scripts/reads_to_ctg_map.py' failed. Command line: 
     python /home/yuke/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py --tmp_path /media/HD6/QXJ/minia-test/BESST_tmp --threads 48 bin3_seq_R1.fq bin3_seq_R2.fq assembly_k41.contigs.fa assembly.lib_0

**Comment by ksahlin** [comment]
Yes, If you provide the error message I can help you.

Best,
K

**Comment by Shirley-Q** [comment]
I'm sorry. I uploaded the picture, but  it did not work.
The error was as followed. Thank you!
Start processing.

Aligning with bwa mem.
Temp directory: /media/HD6/QXJ/minia-test/BESST_tmp
Output path: assembly.lib_0
Stderr file: assembly.lib_0.bwa.1
Make bwa index... Done.
Align with bwa mem... Traceback (most recent call last):
File "/home/yuke/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py", line 360, in
tmp_path, args.bwa_path, args.clear, args.norebuildindex)
File "/home/yuke/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py", line 178, in bwa_mem
stderr=stderr_file)
File "/home/yuke/miniconda2/lib/python2.7/subprocess.py", line 540, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bwa', 'mem', '-t', '48', '-w', '0', '-O', '99', '/media/HD6/QXJ/minia-test/BESST_tmp/genome', 'bin3_seq_R1.fq', 'bin3_seq_R2.fq']' returned non-zero exit status 1
(2019-06-01 10:09:33) Execution of 'python BESST/scripts/reads_to_ctg_map.py' failed. Command line:
python /home/yuke/gatb-minia-pipeline/BESST/scripts/reads_to_ctg_map.py --tmp_path /media/HD6/QXJ/minia-test/BESST_tmp --threads 48 bin3_seq_R1.fq bin3_seq_R2.fq assembly_k41.contigs.fa assembly.lib_0

**Comment by Shirley-Q** [comment]
This is the log file. Thank you very much!




------------------ 原始邮件 ------------------
发件人: "Kristoffer"<notifications@github.com>;
发送时间: 2019年6月1日(星期六) 晚上6:22
收件人: "ksahlin/BESST"<BESST@noreply.github.com>;
抄送: "乔雪姣"<1678141559@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ksahlin/BESST] error about BESST/scripts/reads_to_ctg_map.py(#73)




Yes, If you provide the error message I can help you.
 
Best,
 K

**Comment by ksahlin** [comment]
Hi again sorry for the delay. What if you simply run 

` bwa mem -t 48 -w 0 -O 99 /media/HD6/QXJ/minia-test/BESST_tmp/genome bin3_seq_R1.fq bin3_seq_R2.fq `

from the command line. What does this give you? Do you have bwa installed?
