### ISSUE TITLE
Contigs could be used multiple times ?

### ISSUE THREAD

**Issue by ptranvan** [ksahlin/BESST#76]
Hi,

I was wondering how BESST works during the scaffolding.
Is a contig could be used multiple times (ie: one contig could be in 2 different scaffolds)  ? or one contig is unique and used only once. 

Thanks for your answers.

**Comment by ksahlin** [comment]
Hi @ptranvan,

A contig can only be present in one scaffold in the final output of BESST. Repeated contigs ("repeats") are inferred based on high deviations in coverage and they are not used in the scaffolding. Which of the contigs are classified as repeats can be found with the parameter `--separate_repeats`. This parameter places the inferred repeats in a separate file `repeats.fa` in the output folder. You can also force BESST to use repeats (i.e. place them in one scaffold) by putting `-z [int]` where int is the mena coverage of the contig and is set to something large, say 10000.
