### ISSUE TITLE
Inputfile without mate pair reads

### ISSUE THREAD

**Issue by YuanwenGuo** [ksahlin/BESST#79]
Hello,

I wonder if mate pair data is required for BESST? Is it possible to run scaffolding only with pair end reads?

Thank you,
Yuanwen

**Comment by ksahlin** [comment]
Hi,

Yes it is possible to run BESST with only paired-end reads, just remember to specify the `-orientation` parameter correctly (`fr` being the default orientation of paired-end reads).

Best,
Kristoffer

**Comment by YuanwenGuo** [comment]
Great! Thanks a lot for the help!

Best,
Yuanwen
