### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by ardy20** [ksahlin/BESST#82]
Hello

Can BESST 2.8.8 be used in multithreading option? I see that there is no such an option when I installed it via conda.

usage: BESST [-h] -c CONTIGFILE -f BAMFILES [BAMFILES ...] -orientation
             ORIENTATION [ORIENTATION ...] [-r READLEN [READLEN ...]]
             [-m MEAN [MEAN ...]] [-s STDDEV [STDDEV ...]] [-z COVCUTOFF]
             [-z_min LOWER_COVCUTOFF] [-T THRESHOLD [THRESHOLD ...]]
             [-e EDGESUPPORT [EDGESUPPORT ...]] [-k MINSIZE [MINSIZE ...]]
             [-filter_contigs CONTIG_FILTER_LENGTH] [--min_mapq MIN_MAPQ]
             [--iter PATH_THRESHOLD] [--score_cutoff SCORE_CUTOFF]
             [--max_extensions MAX_EXTENSIONS] [-a HAPLRATIO]
             [-b HAPLTHRESHOLD] [-K KMER] [-M MMER] [-g] [-o OUTPUT] [-d] [-y]
             [-q] [--no_score] [-devel] [-plots] [--separate_repeats]
             [--NO_ILP] [--FASTER_ILP] [--print_scores] [--dfs_traversal]
             [--bfs_traversal] [-max_contig_overlap MAX_CONTIG_OVERLAP]
             [--version]

**Comment by ksahlin** [comment]
Not supported, but BESST is usually fast, see issue #71
